name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v5

      - name: Setup Node.js 20 👷🏻
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies ⏬
        run: npm ci

      - name: Build artifacts 🏗️
        run: npm run build

      - name: Release 🚀
        uses: cycjimmy/semantic-release-action@v5.0.0
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
